<a href="https://colab.research.google.com/github/leeesoraaa/TIL/blob/main/data%20analysis/colab/04_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터(Data)
1. 통계분석은 데이터를 다루는 것이므로 데이터에서 본질적인 의미를 찾는다.
2. 변수의 종류
  - 질적 변수: 2진 변수라고도 부른다. 남성과 여성, 흡연여부 등 값이 2개 뿐인 변수로 명의 척도와 순서 척도가 있다.
  - 양적 변수: 양을 표현하는 변수, 간격 척도와 비례 척도가 있다.
  - 이산형 변수: 0, 1, 2,...와 같이 하나하나의 값을 취하는 변수로 서로 인접한 숫자 사이에 값이 존재하지 않는다.
  - 연속형 변수: 연속적인 값을 취할 수 있는 변수로 어떤 숫자 사이에도 반드시 숫자가 존재한다.

In [1]:
import numpy as np
import pandas as pd

# 매직 명령어(Magic Command)
- IPython(Jupyter notebook)에서 제공하는 add_function
- 접두사 %의 경우: 한 줄의 코드에서만 실행
- 접두사 %%의 경우: 여러 줄, 즉 한 셀의 내용 전체를 실행

In [ ]:
%%writefile sport_test.csv
학생번호,학년,악력,윗몸일으키기,점수,순위
1, 1, 40.2, 34, 15, 4
2, 1, 34.2, 14, 7, 10
3, 1, 28.8, 27, 11, 7
4, 2, 39.0, 27, 14, 5
5, 2, 50.9, 32, 17, 2
6, 2, 36.5, 20, 9, 9
7, 3, 36.6, 31, 13, 6
8, 3, 49.2, 37, 18, 1
9, 3, 26.0, 28, 10, 8
10, 3, 47.4, 32, 16, 3

Overwriting sport_test.csv


In [ ]:
# index_col: 인덱스로 사용할 컬럼명
df = pd.read_csv('sport_test.csv', index_col='학생번호')
df

학년    악력  윗몸일으키기  점수  순위
학생번호                          
1      1  40.2      34  15   4
2      1  34.2      14   7  10
3      1  28.8      27  11   7
4      2  39.0      27  14   5
5      2  50.9      32  17   2
6      2  36.5      20   9   9
7      3  36.6      31  13   6
8      3  49.2      37  18   1
9      3  26.0      28  10   8
10     3  47.4      32  16   3

In [ ]:
df['악력']

학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4
Name: 악력, dtype: float64

In [ ]:
df.columns

Index(['학년', '악력', '윗몸일으키기', '점수', '순위'], dtype='object')

In [ ]:
df.shape

(10, 5)

# 기초 통계 분석
- 데이터의 특징을 파악하는 방법
1. 평균이나 분산 등의 수치 지표에 따라 데이터를 요약
2. 그래프를 이용하여 시각화를 통해 데이터를 분석


In [ ]:
# 출력된 소숫점의 자릿수 제한
%precision 3
# DataFrame의 출력될 값의 소숫점이하 3자리로 제한
# pd.set_option('precision', 3)

'%.3f'

In [ ]:
# numpy를 통해 소숫점 자릿수를 제한
np.set_printoptions(precision=3)

In [ ]:
pd.options.display.float_format = '{:.3f}'.format

In [ ]:
# numpy에서 실수 출력을 설정
np.set_printoptions(formatter={'float_kind':lambda x:"{0:0.3f}".format(x)})

In [ ]:
%%writefile scores_em.csv
student_number,english,mathematics
1,42,65
2,69,80
3,56,63
4,41,63
5,57,76

Writing scores_em.csv


In [ ]:
df2 = pd.read_csv('scores_em.csv', index_col = 'student_number')
df2

english  mathematics
student_number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [ ]:
scores = np.array(df2['english'])
scores

array([42, 69, 56, 41, 57])

In [ ]:
scores_df = pd.DataFrame({'score':scores},
                         index=pd.Index(['A', 'B', 'C', 'D', 'E']))
scores_df

score
A     42
B     69
C     56
D     41
E     57

## 평균값(mean): 가장 일반적으로 사용되는 대푯값

In [ ]:
sum(scores)/len(scores)

53.0

In [ ]:
np.mean(scores)

53.0

In [ ]:
# DataFrame, Series 객체에서 mean() 사용
scores_df.mean()   # DataFrame에서는 dtype이 같이 출력됨

score    53.0
dtype: float64

In [ ]:
scores_df['score'].mean()  # Series

53.0

## 중앙값(median): 데이터를 크기 순서대로 나열할 때 정확하게 중앙에 위치한 값

In [ ]:
sorted_df = np.sort(df['윗몸일으키기'])
sorted_df

array([14, 20, 27, 27, 28, 31, 32, 32, 34, 37])

In [ ]:
# 중앙값을 구현하는 함수 정의
n = len(sorted_df)

if n % 2 == 0:
  m0 = sorted_df[(n // 2) - 1]
  m1 = sorted_df[n // 2]
  median = (m0 + m1) / 2
else:
  median = sorted_df[n // 2]

print(median)

29.5


In [ ]:
# numpy
np.median(sorted_df)

29.5

In [ ]:
# DataFrame, Series: 객체명.median()
df['윗몸일으키기'].median()

29.5

## 최빈값(mode): 데이터에서 가장 많이 나타나는 값
- 기본적으로 질적 데이터(범주형 데이터)의 대푯값을 구할 때 사용하는 지표

In [ ]:
pd.Series([1,1,1,2,2,3,3,3,3,3,3,3]).mode()

0    3
dtype: int64

## 편차(deviation): 각 데이터가 평균으로부터 어느 정도 떨어져 있는지를 나타내는 지표

In [ ]:
mean = np.mean(scores)
mean

53.0

In [ ]:
deviation = scores - mean
deviation

array([-11.,  16.,   3., -12.,   4.])

## 분산(variance): 편차의 제곱

In [ ]:
np.mean(deviation ** 2)

109.2

In [ ]:
np.var(scores)

109.2

In [ ]:
df2['english'].var()

136.5

- 분산에는 표본분산과 불편분산의 두 종류가 있다.
- Numpy는 표본분산을 기본 분산으로 사용
- Pandas는 불편분산을 기본 분산으로 사용
- 국내 통계학에서는 불편분산을 기본 분산으로 채택

## 표준편차(standard deviation): 분산에 제곱근을 취한 값

In [ ]:
np.sqrt(np.var(scores, ddof=0))

10.449880382090505

In [ ]:
np.std(scores, ddof=0)

10.449880382090505

## 범위(range): 데이터의 최댓값과 최솟값만으로 산포도를 표현하는 방법
- 분산이나 표준편차와 달리 데이터 전체를 보는 것은 아니다.
- 최댓값과 최솟값의 차이가 크면 산포도가 크고, 그 차이가 작으면 산포도도 작다는 의미
- 이상치가 있을 경우 대푯값으로 사용할 수 없다.

In [ ]:
np.max(scores) - np.min(scores)

28

## 사분위수
- 전체 데이터의 분포를 파악할 떄 사용된다.

In [ ]:
pd.Series(scores).describe()

count     5.000000
mean     53.000000
std      11.683321
min      41.000000
25%      42.000000
50%      56.000000
75%      57.000000
max      69.000000
dtype: float64

In [ ]:
q1 = np.percentile(scores, 25)
q3 = np.percentile(scores, 75)
IQR = q3 - q1

# 데이터 전처리: Feature Scaling(피처 스케일링)
- 서로 다른 변수의 값들의 범위를 일정한 수준으로 맞추는 작업
1. 표준화(StandartScalar)
  - 평균이 0이고, 분산이 1인 가우시안 정규 분포를 가진 값으로 변환
  - z-value라는 표현을 사용
    z = (x - maean())/std()
  
2. 정규화(Normalization)
  - 일반적으로 정규화라는 것은 서로 다른 값들을 통일하기 위해 변환
  - MinMaxScaler: 데이터의 값을 0과 1 사이의 값으로 변환
    단, 음수값이 있으면 -1에서 1사이의 값으로 변환

3. 범주형 데이터(문자) => 정형화를 하기 위해
  - One-Hot encoding(원-핫 인코딩): 문자값을 0과 1의 값으로 변환

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
scaler = StandardScaler()
iris = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

- target: 문자열 범주형 데이터가 정형화된 것

In [5]:
# 데이터프레임(DataFrame): data, index, columns
iris.data  # DF의 data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris_df = pd.DataFrame(iris.data, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

In [8]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [9]:
import seaborn as sns
iris = sns.load_dataset('iris')
print(type(iris))

<class 'pandas.core.frame.DataFrame'>


In [10]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [11]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [12]:
# iris 모든 컬럼(피처) 값이 평균 0에 아주 가까운 값으로, 분산은 1에 가까운 값으로 변환
iris = load_iris()
scaler.fit(iris_df)  # 학습
iris_sc = scaler.transform(iris_df)
iris_sc = pd.DataFrame(data = iris_sc, columns = iris.feature_names)

In [13]:
iris_sc.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

In [14]:
iris_sc.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [15]:
iris_sc.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [24]:
iris = load_iris()
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_mms = scaler.transform(iris_df)
iris_mms = pd.DataFrame(data = iris_mms, columns = iris.feature_names)
iris_mms.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667

In [25]:
iris_mms.min()

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

In [26]:
iris_mms.max()

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

In [19]:
# fit_transform() : 데이터 전처리
# fit / predict : 머신러닝

In [20]:
import seaborn as sns
iris = sns.load_dataset('iris')

In [21]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [22]:
z_value = (iris['sepal_length'] - np.mean(iris['sepal_length'])) / np.std(iris['sepal_length'])
z_value

0     -0.900681
1     -1.143017
2     -1.385353
3     -1.506521
4     -1.021849
         ...   
145    1.038005
146    0.553333
147    0.795669
148    0.432165
149    0.068662
Name: sepal_length, Length: 150, dtype: float64

# 데이터 인코딩
- 레이블 인코딩(Label Encoding)
- 원-핫 인코딩(One-Hot Encoding)

In [28]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '선풍기', '에어프라이어', '에어프라이어']

lbe.fit(items)
item_lbe = lbe.transform(items)
print(item_lbe)

[0 1 4 5 2 2 2 3 3]


- OneHotEncoder로 변환하기 전에 모든 문자열 값이
숫자형으로 변환되어야 한다.
- 입력값으로 2차원 데이터가 필요하다.

In [32]:
item_lbe = item_lbe.reshape(-1, 1)  # 차원만 늘어난다.
item_lbe

array([[0],
       [1],
       [4],
       [5],
       [2],
       [2],
       [2],
       [3],
       [3]])

In [33]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
ohe.fit(item_lbe)
item_ohe = ohe.transform(item_lbe)
print(item_ohe.toarray())

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
