# Numpy
- C언어로 구현된 파이썬 라이브러리
- 고성능 수치계산을 위해 제작
- Numerical Python
- 벡터 및 행렬 연산에 매우 편리한 기능 제공
- Pandas와 matplotlib과 더블어 데이터분석에 필수 라이브러리
- 기본적으로 array 단위로 데이터 처리
- 대표적인 자료형 : ndarray 객체

## Numpy

In [2]:
# numpy 모듈 불러오기
import numpy as np

## Array 정의 및 사용

In [2]:
# Python의 List 이용
a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [3]:
b = [1, 2, 3, 4, 5]
b

[1, 2, 3, 4, 5]

In [4]:
arr1 = np.array(a)
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [6]:
# array 형태(크기) 확인
arr1.shape

(5,)

In [7]:
# array 자료형 확인
arr1.dtype

dtype('int32')

## 1.3 배열 생성 : Numpy가 제공하는 함수를 이용한 단순 배열 생성
- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linespace, logspace

In [8]:
# 0인 배열 생성 : zeros(배열의 크기)
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [9]:
b = np.zeros(5, dtype="i")
b

array([0, 0, 0, 0, 0], dtype=int32)

- numpy 자료형, dtype의 접두사
- "i" : 정수형
- "u" : uint(unsign int), 부호가 없는 정수
- "f" : float
- "b" : 논리형(bool)
- "c" : 복소수(complex)
- "s" : 문자열(string)

In [10]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [11]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
c = np.zeros((5, 2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [13]:
e = np.ones((2, 3, 4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
# 기존의 배열의 크기를 그대로 사용하여 배열 생성
## zeros_like
## ones_like
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
f = np.ones_like(b)
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
g = np.empty((4, 3))
g

array([[1.46695114e-311, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 2.14321575e-312, 3.69776220e-062],
       [5.27390942e-091, 2.74954875e+180, 8.40869129e+164],
       [1.90352982e+185, 3.99910963e+252, 9.13597212e+169]])

In [17]:
# range() : 순차리스트, 수열생성 함수
# range(5) : 0, 1, 2, 3, 4
# range(1, 10) : 1, 9
# arange() : Numpy 버전의 range 명령어이다.
np.arange(10) # 0 ~ n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [20]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치행렬
- 행과 열을 바꾸는 기능
- T

In [21]:
A = np.array([[1, 2, 3],[4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열의 크기 변형
- 배열의 크기 속성 : shape, 배열명.속성
- 배열의 크기 변경 : reshape

In [24]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
a.shape

(12,)

In [26]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [29]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [30]:
# 다차원 배열을 1차원 배열로 생성하는 flatten, ravel 메서드
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [35]:
x.shape

(5,)

In [36]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [37]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [38]:
# 차원만 증가시키는 newaxis
x

array([0, 1, 2, 3, 4])

In [39]:
x.shape

(5,)

In [40]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

# Numpy 배열의 연산

In [ ]:
## 반복문을 썼을 때와 반복문을 쓰지 않았을 때의 시간 차이

In [3]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [4]:
%%time
res = np.zeros_like(x)
for i in range(10000):
    res[i] = x[i] + y[i]

CPU times: total: 15.6 ms
Wall time: 8.26 ms


In [5]:
res[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [6]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [7]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [8]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [9]:
a == b  # 요소 단위로 계산

array([False,  True, False,  True])

In [10]:
a >= b

array([False,  True,  True,  True])

In [11]:
np.all(a==b) # 요소 전체

False

In [12]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [13]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [14]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [15]:
np.log(1 + a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [18]:
x = np.arange(12).reshape(3, 4) # 0~11의 요소를 가진 1차원의 배열을 3행 4열의 2차원의 배열로 변형

In [19]:
100 *x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

##  브로드캐스팅(broadcasting)
 - 서로 크기가 다른 배열의 사칙연산을 수행하는 기능
 - 크기가 작은 배열이 자동적으로 크기가 큰 배열의 크기로 맞춰지는 기능

In [20]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [22]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [23]:
x + 1

array([1, 2, 3, 4, 5])

In [24]:
y = np.arange(12).reshape(3, 4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
y + 1  # 차원이 다른 값들의 사칙연산 (브로드캐스팅)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
z = np.ones_like(y)
z

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
y + z  # == y + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 그룹함수 (=차원 축소 연산)
- 최대/최소: min, max(최대/최소 값을 반환), argmin, argmax(최대/최소 값의 인덱스를 반환)
- 기초통계: sum, mean, median, std, var
- 논리연산: all, any

In [28]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [29]:
np.sum(x)  # numpy

10

In [30]:
x.sum()   # python

10

In [31]:
x = np.array([1, 3, 2])
x

array([1, 3, 2])

In [32]:
np.min(x)  # numpy

1

In [33]:
x.min()  # python

1

In [34]:
x.argmin()  # 최소값의 위치

0

In [35]:
x.argmax()  # 최대값의 위치

1

In [36]:
x.mean()

2.0

In [37]:
np.mean(x)

2.0

In [38]:
np.median(x)

2.0

In [39]:
y = np.array([1, 2, 3, 1])
y

array([1, 2, 3, 1])

In [40]:
np.median(y)

1.5

In [41]:
y.median()  # 파이썬에는 median()이 없다.

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [42]:
np.all([True, True, False])  # 모두 참인가?

False

In [43]:
np.any([True, True, False])  # 어느 거 하나라도 참인가?

True

In [44]:
a = np.zeros((100, 100), dtype='i')
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [45]:
np.any(a != 0)

False

In [46]:
np.all(a == 0)

True

In [47]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,4])
c = np.array([6,4,4,5])

In [50]:
((a <= b) & (b <= c)).all()

True

- 축(axis): axis = 0(열), axis = 1(행), default(axis=0)

In [51]:
x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [52]:
x.sum()

6

In [53]:
x.sum(axis=0)

array([3, 3])

In [54]:
x.sum(axis=1)

array([2, 4])

## 정렬(sort)
- 2차원이상일 경우에는 행이나 열을 각각 따로 정렬한다.
- axis = 0이면 각 열을 기준으로 정렬, axis = 1이면 각 행을 기준으로 정렬
- 정렬에서 default axis = 1
- axis = -1은 axis = 1 과 같다.

In [60]:
a = np.array([[4,3,5,7],
             [1,12,11,9],
             [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [56]:
np.sort(a) # axis = 1(axis = -1과 동일)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [57]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [58]:
np.sort(a, axis=-1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [59]:
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [61]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [62]:
# 정렬을 하지 않고 순서만 알고 싶다면 argsort 명령을 사용한다.
## argsort: 정렬 인덱스 출력
a = np.array([4, 2, 3, 8])
b = np.argsort(a)
b

array([1, 2, 0, 3], dtype=int64)

In [63]:
a[b]

array([2, 3, 4, 8])

## Fancy Indexion: 펜시인덱싱
 - boolean 인덱싱을 이용하는 것
 - 마스크 인덱싱
 - 규칙이 일정하지 않지만 원하는 데이터를 추출하고자 할 때 사용한다.

In [64]:
names = np.array(['park', 'park', 'kim', 'joan', 'lee', 'park', 'hong', 'park'])
names

array(['park', 'park', 'kim', 'joan', 'lee', 'park', 'hong', 'park'],
      dtype='<U4')

In [65]:
names.shape  # 1차원 배열, 8개 요소

(8,)

In [66]:
# 정규분포: np.random.randn(), 평균=0, 표준편차=1
# 0~1 사이의 난수 발생
data = np.random.randn(8, 4)  # 표준 정규분포 난수(8행 4열)
data

array([[-0.4677975 , -0.43463794,  0.34152843,  1.40733221],
       [-0.60233348,  0.94900927, -0.62743396,  0.81218609],
       [-0.68978495, -0.9296477 ,  0.2002509 , -2.07166355],
       [-0.3431542 , -0.14614195, -1.606254  ,  0.34090443],
       [-0.2600008 , -0.77615178, -0.05336538, -1.96369425],
       [ 0.66167275,  0.3365099 ,  1.12696464,  0.50090021],
       [-0.7801516 , -0.47518442, -0.66742633,  0.06626301],
       [-0.75395313, -0.32960909, -0.71027934,  0.25366488]])

In [67]:
data.shape

(8, 4)

In [68]:
index = (names == 'park')
data[index, :]

array([[-0.4677975 , -0.43463794,  0.34152843,  1.40733221],
       [-0.60233348,  0.94900927, -0.62743396,  0.81218609],
       [ 0.66167275,  0.3365099 ,  1.12696464,  0.50090021],
       [-0.75395313, -0.32960909, -0.71027934,  0.25366488]])

In [69]:
# 요소가 'kim'인 행의ㅣ 데이터만 추출
data[names == 'kim', :]

array([[-0.68978495, -0.9296477 ,  0.2002509 , -2.07166355]])

In [70]:
data[2,:]

array([-0.68978495, -0.9296477 ,  0.2002509 , -2.07166355])

In [71]:
# kim과 hong
data[(names=='kim') | (names == 'hong'),:]

array([[-0.68978495, -0.9296477 ,  0.2002509 , -2.07166355],
       [-0.7801516 , -0.47518442, -0.66742633,  0.06626301]])

In [72]:
data

array([[-0.4677975 , -0.43463794,  0.34152843,  1.40733221],
       [-0.60233348,  0.94900927, -0.62743396,  0.81218609],
       [-0.68978495, -0.9296477 ,  0.2002509 , -2.07166355],
       [-0.3431542 , -0.14614195, -1.606254  ,  0.34090443],
       [-0.2600008 , -0.77615178, -0.05336538, -1.96369425],
       [ 0.66167275,  0.3365099 ,  1.12696464,  0.50090021],
       [-0.7801516 , -0.47518442, -0.66742633,  0.06626301],
       [-0.75395313, -0.32960909, -0.71027934,  0.25366488]])

In [73]:
# 0번째 열의 값이 0보다 작은 행을 추출
data[:,0] < 0  # True/False만 뜸 == 마스크비트
data[data[:,0] < 0,:]

array([[-0.4677975 , -0.43463794,  0.34152843,  1.40733221],
       [-0.60233348,  0.94900927, -0.62743396,  0.81218609],
       [-0.68978495, -0.9296477 ,  0.2002509 , -2.07166355],
       [-0.3431542 , -0.14614195, -1.606254  ,  0.34090443],
       [-0.2600008 , -0.77615178, -0.05336538, -1.96369425],
       [-0.7801516 , -0.47518442, -0.66742633,  0.06626301],
       [-0.75395313, -0.32960909, -0.71027934,  0.25366488]])

In [75]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열의 값만 추출
data[data[:,0] < 0,2:4]

array([[ 0.34152843,  1.40733221],
       [-0.62743396,  0.81218609],
       [ 0.2002509 , -2.07166355],
       [-1.606254  ,  0.34090443],
       [-0.05336538, -1.96369425],
       [-0.66742633,  0.06626301],
       [-0.71027934,  0.25366488]])

In [76]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열의 값을 0으로 치환
data[data[:,0] < 0,2:4] = 0
data

array([[-0.4677975 , -0.43463794,  0.        ,  0.        ],
       [-0.60233348,  0.94900927,  0.        ,  0.        ],
       [-0.68978495, -0.9296477 ,  0.        ,  0.        ],
       [-0.3431542 , -0.14614195,  0.        ,  0.        ],
       [-0.2600008 , -0.77615178,  0.        ,  0.        ],
       [ 0.66167275,  0.3365099 ,  1.12696464,  0.50090021],
       [-0.7801516 , -0.47518442,  0.        ,  0.        ],
       [-0.75395313, -0.32960909,  0.        ,  0.        ]])

# 기술통계분석

In [77]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수: len

In [78]:
len(x)

26

## 평균: mean

In [79]:
np.mean(x)

4.8076923076923075

## 분산: var

In [80]:
np.var(x)

115.23224852071006

In [81]:
# 비편향 분산
np.var(x, ddof=1)

119.84153846153846

## 표준편차: std

In [82]:
np.std(x)

10.734628476137871

## 최대값과 최소값: max, min

In [83]:
np.max(x)

23

In [84]:
np.min(x)

-24

## 중위수: median

In [85]:
np.median(x)

5.0

## 사분위수: quantile, percentile

In [86]:
np.percentile(x,0) # 최소값

-24.0

In [87]:
np.percentile(x, 25) # 1사분위수

0.0

# 난수(random number)

## 시드설정(seed): 0과 같거나 큰 정수

In [88]:
np.random.seed(0)

In [89]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [90]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [91]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [94]:
np.random.seed(0)

In [95]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [100]:
arr1 = np.random.random((3, 3))  # 0~1 사이의 실수 균등 분포
arr1

array([[0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 ]])

In [98]:
arr2 = np.random.normal(2,1,(3,2)) # 평균(2), 편차(1)인 정규분포
arr2

array([[2.44386323, 2.33367433],
       [3.49407907, 1.79484174],
       [2.3130677 , 1.14590426]])

In [99]:
arr3 = np.random.randn(2, 3) # 표준 정규분포(평균 0, 편차 1)
arr3

array([[-2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567]])

In [101]:
arr4 = np.random.randint(0, 10,(2, 2))
arr4

array([[9, 9],
       [3, 6]])

## 데이터 샘플링(sampling), shuffle 명령과 같다
- np.choice(배열, size, replace, p)
- 배열: arange(n)

In [103]:
np.random.choice(5, 5, replace=False)  # replace=False: 중복 불가

array([1, 4, 0, 3, 2])

In [104]:
np.random.choice(5, 3, replace=False)  # 0~4 중 3개

array([2, 4, 0])

In [105]:
np.random.choice(5, 10, replace=False)  # Error(중복없이 10개 추출 불가)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [106]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([0, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [107]:
# 0에서 1 사이의 균일분포
np.random.rand(10)

array([0.33800761, 0.67475232, 0.31720174, 0.77834548, 0.94957105,
       0.66252687, 0.01357164, 0.6228461 , 0.67365963, 0.971945  ])

In [108]:
np.random.rand(3,5)

array([[0.87819347, 0.50962438, 0.05571469, 0.45115921, 0.01998767],
       [0.44171092, 0.97958673, 0.35944446, 0.48089353, 0.68866118],
       [0.88047589, 0.91823547, 0.21682214, 0.56518887, 0.86510256]])

In [109]:
# np.random.randint(low, high=None, size)
np.random.randint(10, 20, size=10)

array([12, 19, 11, 14, 16, 18, 12, 13, 10, 10])

In [110]:
np.random.randint(10, 20, size =(3, 5))

array([[16, 10, 16, 13, 13],
       [18, 18, 18, 12, 13],
       [12, 10, 18, 18, 13]])

## 정수 데이터 카운팅
- unique: 중복을 제거하고 중복되지 않은 값
- return_counts = True, 각 값의 갯수

In [111]:
np.unique([11,11,2,2,3,3])

array([ 2,  3, 11])

In [112]:
a = np.array(['a', 'b', 'c', 'b', 'a'])
a

array(['a', 'b', 'c', 'b', 'a'], dtype='<U1')

In [113]:
np.unique(a)

array(['a', 'b', 'c'], dtype='<U1')

In [114]:
index, count = np.unique(a, return_counts=True)

In [115]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [116]:
count

array([2, 2, 1], dtype=int64)

# Data Analysis - 2nd

In [117]:
# zeros, ones, full, eye
a = np.full((2, 3), 5)  # 2행 3열을 5로 채워라
a

array([[5, 5, 5],
       [5, 5, 5]])

In [118]:
# eye: 정방행렬(행과 열의 수가 같은)
b = np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [119]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
arr2d[2]  # 인덱스가 1개만 주어진다면 행을 뜻한다.

array([7, 8, 9])

In [121]:
arr2d[2][0] # 2행 1열

7

In [122]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [123]:
b = a # b = a[:] 얕은복사(주소공유)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [124]:
a[0,0] = 100
print(a)
print(b)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [125]:
# copy(): 깊은 복사
c = a.copy()
c

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [127]:
a[1,1] = 100
print(c)
print(a)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5 100   7   8]
 [  9  10  11  12]]


In [128]:
array = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [130]:
arr1 = array[0].copy()
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
array[0][1]

array([4, 5, 6])

In [132]:
array[0,1, :]

array([4, 5, 6])

In [135]:
arr = np.arange(15).reshape(3, -1)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [134]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [137]:
ary1 = np.array([1,2,2,3,4,4,5,6,7,8,8,8])
np.random.shuffle(ary1)  # 요소들을 섞어라

In [138]:
ary1

array([5, 8, 2, 4, 1, 6, 3, 4, 8, 2, 8, 7])