In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
X = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([[0],[1],[1],[0]])  # XOR

In [13]:
model = Sequential()  # Sequential 객체 선언
model.add(Dense(1, input_dim=2, activation='sigmoid')) # 신경망 구조 생성
model.summary()  # 신경망 구조 보여줌

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3 (12.00 Byte)
Trainable params: 3 (12.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.compile(optimizer='adam',   # 오차를 줄여나갈 방법(경사하강법)
              loss='binary_crossentropy',  # 손실함수(교차엔트로피)
              metrics=['acc'])   # 평가지표

In [15]:
model.fit(X, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 460ms/step - loss: 0.8348 - acc: 0.7500
Epoch 2/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.8343 - acc: 0.7500
Epoch 3/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.8338 - acc: 0.7500
Epoch 4/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.8334 - acc: 0.7500
Epoch 5/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.8329 - acc: 0.7500
Epoch 6/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.8324 - acc: 0.7500
Epoch 7/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.8319 - acc: 0.7500
Epoch 8/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.8315 - acc: 0.7500
Epoch 9/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.8310 - acc: 0.7500
Epoch 10/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.8305 - acc: 0.7500
Epoch 11/1000
1/1 [==============================] - 0s 10ms/

In [16]:
model.fit(X, y, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 21ms/step - loss: 0.7010 - acc: 0.5000
Epoch 2/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.7010 - acc: 0.5000
Epoch 3/2000
1/1 [==============================] - 0s 15ms/step - loss: 0.7010 - acc: 0.5000
Epoch 4/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.7010 - acc: 0.5000
Epoch 5/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.7010 - acc: 0.5000
Epoch 6/2000
1/1 [==============================] - 0s 13ms/step - loss: 0.7010 - acc: 0.5000
Epoch 7/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.7010 - acc: 0.5000
Epoch 8/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.7010 - acc: 0.5000
Epoch 9/2000
1/1 [==============================] - 0s 13ms/step - loss: 0.7010 - acc: 0.5000
Epoch 10/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.7010 - acc: 0.5000
Epoch 11/2000
1/1 [==============================] - 0s 14m

In [17]:
model.predict([[1,1]])

1/1 [==============================] - 0s 69ms/step


array([[0.5064189]], dtype=float32)

# 은닉층과 오차 역전파

## relu 활성화 함수

In [18]:
model = Sequential()  # Sequential 객체 선언
model.add(Dense(32, input_dim=2, activation='relu')) # 은닉층
model.add(Dense(1, input_dim=2, activation='sigmoid')) # 신경망 구조 생성
model.summary()  # 신경망 구조 보여줌

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 32)                96        
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 129 (516.00 Byte)
Trainable params: 129 (516.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.compile(optimizer='adam',   # 오차를 줄여나갈 방법(경사하강법)
              loss='binary_crossentropy',  # 손실함수(교차엔트로피)
              metrics=['acc'])

In [20]:
model.fit(X, y, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 1s 799ms/step - loss: 0.7081 - acc: 0.7500
Epoch 2/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.7065 - acc: 0.7500
Epoch 3/2000
1/1 [==============================] - 0s 9ms/step - loss: 0.7049 - acc: 0.7500
Epoch 4/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.7034 - acc: 0.7500
Epoch 5/2000
1/1 [==============================] - 0s 13ms/step - loss: 0.7019 - acc: 0.7500
Epoch 6/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.7004 - acc: 0.7500
Epoch 7/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.6990 - acc: 0.7500
Epoch 8/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.6977 - acc: 0.7500
Epoch 9/2000
1/1 [==============================] - 0s 8ms/step - loss: 0.6965 - acc: 0.7500
Epoch 10/2000
1/1 [==============================] - 0s 16ms/step - loss: 0.6953 - acc: 0.7500
Epoch 11/2000
1/1 [==============================] - 0s 11ms

In [21]:
model.predict([[1,1]])

1/1 [==============================] - 1s 1s/step


array([[0.00919599]], dtype=float32)

In [22]:
model = Sequential()  # Sequential 객체 선언
model.add(Dense(32, input_dim=2, activation='relu')) # 은닉층(노드 32개)
model.add(Dense(12, input_dim=2, activation='relu')) # 은닉층(노드 12개)
model.add(Dense(1, input_dim=2, activation='sigmoid')) # 신경망 구조 생성
model.summary()  # 신경망 구조 보여줌

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 32)                96        
                                                                 
 dense_6 (Dense)             (None, 12)                396       
                                                                 
 dense_7 (Dense)             (None, 1)                 13        
                                                                 
Total params: 505 (1.97 KB)
Trainable params: 505 (1.97 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.compile(optimizer='adam',   # 오차를 줄여나갈 방법(경사하강법)
              loss='binary_crossentropy',  # 손실함수(교차엔트로피)
              metrics=['acc'])

In [26]:
model.fit(X, y, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 12ms/step - loss: 0.1960 - acc: 1.0000
Epoch 2/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.1940 - acc: 1.0000
Epoch 3/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.1920 - acc: 1.0000
Epoch 4/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.1899 - acc: 1.0000
Epoch 5/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.1879 - acc: 1.0000
Epoch 6/2000
1/1 [==============================] - 0s 9ms/step - loss: 0.1859 - acc: 1.0000
Epoch 7/2000
1/1 [==============================] - 0s 13ms/step - loss: 0.1839 - acc: 1.0000
Epoch 8/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.1819 - acc: 1.0000
Epoch 9/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.1800 - acc: 1.0000
Epoch 10/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.1781 - acc: 1.0000
Epoch 11/2000
1/1 [==============================] - 0s 10ms

In [27]:
model.predict([[1,1]])

1/1 [==============================] - 0s 57ms/step


array([[0.00028184]], dtype=float32)

## 하이퍼볼릭 탄젠트(tanh) 활성화 함수

In [28]:
model = Sequential()  # Sequential 객체 선언
model.add(Dense(32, input_dim=2, activation='tanh')) # 은닉층(노드 32개)
model.add(Dense(12, input_dim=2, activation='tanh')) # 은닉층(노드 12개)
model.add(Dense(1, input_dim=2, activation='sigmoid')) # 신경망 구조 생성
model.summary()  # 신경망 구조 보여줌

model.compile(optimizer='adam',   # 오차를 줄여나갈 방법(경사하강법)
              loss='binary_crossentropy',  # 손실함수(교차엔트로피)
              metrics=['acc'])

model.fit(X, y, epochs=1000)

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 32)                96        
                                                                 
 dense_9 (Dense)             (None, 12)                396       
                                                                 
 dense_10 (Dense)            (None, 1)                 13        
                                                                 
Total params: 505 (1.97 KB)
Trainable params: 505 (1.97 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/1000
1/1 [==============================] - 1s 835ms/step - loss: 0.6872 - acc: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.6859 - acc: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6847 - acc: 0.5000
Epoch

## 소프트플러스(softplus) 활성화 함수

In [29]:
model = Sequential()  # Sequential 객체 선언
model.add(Dense(32, input_dim=2, activation='softplus')) # 은닉층(노드 32개)
model.add(Dense(12, input_dim=2, activation='softplus')) # 은닉층(노드 12개)
model.add(Dense(1, input_dim=2, activation='sigmoid')) # 신경망 구조 생성
model.summary()  # 신경망 구조 보여줌

model.compile(optimizer='adam',   # 오차를 줄여나갈 방법(경사하강법)
              loss='binary_crossentropy',  # 손실함수(교차엔트로피)
              metrics=['acc'])

model.fit(X, y, epochs=1000)

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_11 (Dense)            (None, 32)                96        
                                                                 
 dense_12 (Dense)            (None, 12)                396       
                                                                 
 dense_13 (Dense)            (None, 1)                 13        
                                                                 
Total params: 505 (1.97 KB)
Trainable params: 505 (1.97 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/1000
1/1 [==============================] - 1s 1s/step - loss: 0.7137 - acc: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 18ms/step - loss: 0.7072 - acc: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.7019 - acc: 0.5000
Epoch 4/